[build]
  command = "npm run docs:build"
  publish = ".vitepress/dist"

[[redirects]]
  from = "/aem-note/*"
  to = "/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
